

FIND_PATH(RABBITMQ_INCLUDE_DIR NAMES rabbitmq-c HINTS ${THIRD_PARTY_PATH}/rabbitmq/include)
FIND_FILE(RABBITMQ_LIB librabbitmq.a HINTS ${THIRD_PARTY_PATH}/rabbitmq/lib)

ADD_LIBRARY(RabbitMQ STATIC IMPORTED)
	SET_TARGET_PROPERTIES(RabbitMQ PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${RABBITMQ_INCLUDE_DIR}"
			IMPORTED_LOCATION "${RABBITMQ_LIB}"
	)